name: Pandoc Website Builder

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Start Github Actions v1"
      - run: echo "Build Index"
      - uses: docker://pandoc/core:3.5
        with:
          args: >-
            ../index.md -s -f gfm -t html5 --template=../template/index.html --defaults=../defaults/params_index.yaml --output ../index.html
      
      # - run: echo "Build Sections"
      # - run: echo "End Github Actions"
